language: r
sudo: required
cache: packages

os:
  - linux

r_packages:
  - devtools
  - roxygen2

script:
  - |
    R CMD build .
    travis_wait 180 R CMD check --no-build-vignettes --no-manual --as-cran sentometrics*tar.gz
  - Rscript -e 'devtools::install(); devtools::test()'

r:
  # - devel
  # - release
  - oldrel

after_success:
- Rscript -e 'covr::codecov()'
